<?php
/**
 * Real Google reviews for Higher Truth Tattoo (Mark C. Merchant),
 * transcribed from client-supplied screenshots. All 5-star.
 * Home shows the first 12; About shows the full set.
 * 'when' is the relative age shown on Google at capture time.
 */
return [
    ['name' => 'Shane M',            'stars' => 5, 'when' => 'a week ago', 'text' => "Mark Merchant did a fantastic job with my first ever tattoo. He was very professional, knowledgeable, talented and a great person to talk to while he's working. I highly recommend Mark for any tattoo work."],
    ['name' => 'Courtney R',         'stars' => 5, 'when' => '7 years ago', 'text' => "I cannot say enough good things about Mark and his work! I have gotten multiple bright & bold tattoos from him and I will not go anywhere else! His work stands alone, but in addition to that, Mark is an awesome guy. He truly cares about giving you the best experience and takes the time to work with you and get you a great tattoo. He is easy to talk to and I always enjoy hanging out with him. I highly recommend him!"],
    ['name' => 'Renee Chappell',     'stars' => 5, 'when' => 'a year ago', 'text' => "I've known Mark since 2011 and I can say without a doubt, he is a kind, professional, creative, and extremely talented artist. He's been tattooing in the Dallas area for decades. His knowledge of tattooing is phenomenal, as is his music taste. If his designs are what you are looking for I'd definitely give him a call and take the time to get to know him before making that big decision. He is a great communicator."],
    ['name' => 'Flint Kemper',       'stars' => 5, 'when' => '6 years ago', 'text' => "I am a tattoo collector and once seeing Mark's online portfolio I knew I wanted to acquire some work from him. From the online booking to my first session all was smooth. Mark was open and honest about taking my idea and making it to stand the test of time. He thoroughly discussed design, color palette to be used and made sure I was good with everything he was discussing. Two sessions went by quickly where I ended up with a beautiful piece of art on my body. If you are local or from far away make sure to get with Mark for your next tattoo, you will not be disappointed."],
    ['name' => 'Alex Dhanani',       'stars' => 5, 'when' => '6 years ago', 'text' => "Mark is the most incredible tattoo artist I have been to. He takes time to understand the art that you want and makes sure it's in the best quality for his clients. I have been tattooed multiple times by Mark and the line-work is insanely clean and my expectations are always exceeded. Definitely recommend coming here for a tattoo! I guarantee you'll leave as happy and satisfied as myself."],
    ['name' => 'Linda Lopez',        'stars' => 5, 'when' => '5 years ago', 'text' => "Mark has been my tattoo artist for the last 4 years. I want to start off by saying that he is the most professional artist that I have ever been to. You're always greeted with a smile and such great vibes. I've never been greeted with such hospitality elsewhere. He's professional and always committed to giving you a tattoo that will last a lifetime. His work is beautiful and each session is enlightening. An added bonus is that I genuinely appreciate how effectively he communicates before and after a tattoo session. Ultimately, he's genuine and one of a kind. I wouldn't ever want to go anywhere else for a tattoo other than Higher Truth Tattoo!"],
    ['name' => 'Elijah Garcia',      'stars' => 5, 'when' => '8 years ago', 'text' => "This was my first time going into a private studio and my experience was amazing! From the moment I walked in, I felt very welcomed. The space is unique and very cozy. Mark is very friendly and will listen to all your ideas. Mark took his time to understand what I wanted and drew a sketch of my tattoo which came out better than what I envisioned originally. I'm extremely grateful and happy with his work. It was an honor to work with Mark. I'll definitely be back for more!"],
    ['name' => 'Hartli Young',       'stars' => 5, 'when' => '5 years ago', 'text' => "Honestly, the best tattoo experience I've ever had. If you're looking for an artist that will sit down and take the time to talk about the design with you and make your experience as comfortable as possible, then Mark is your guy. His designs are so clean and unique, and I'm so happy with the final product. 10/10, can't recommend him enough. Thank you, Mark!"],
    ['name' => 'Chris Browne',       'stars' => 5, 'when' => '6 years ago', 'text' => "Great experience with Mark today! Was lucky enough to get my first tattoo in 20 years from him and he just happened to have done my last one back then on the same arm! His freehand approach really allows him to fit the work on the muscle and I really dig the placement. He has a cool studio/gallery in a peaceful location. He keeps an amazingly clean studio and makes you feel comfortable and it's obvious that he knows exactly what to do. If you wanna have a great experience getting work done by someone that cares about themselves and others then Mark is your artist!"],
    ['name' => 'Mariela Morales',    'stars' => 5, 'when' => '7 years ago', 'text' => "Finally got around to getting my first tattoo done and I couldn't be happier with Mark's work! He did a great job explaining the complete process and made me feel comfortable through the experience. His artworks are a masterpiece. My husband and I both recommend him greatly to anyone who's looking for a quality piece."],
    ['name' => 'Megan Nieves',       'stars' => 5, 'when' => '8 years ago', 'text' => "Mark is an extremely talented artist as well as a kind and open human. His space is beautiful and intimate, quite the opposite of what you think of when you think of a tattoo shop. Crisp, white walls make the place feel more like an art gallery, which is perfect because you will be leaving with a true work of art on your body. Mark took great care to understand exactly what I wanted out of my piece, and the sketch he provided was better than anything I could have asked for. He's soothing and conversational, and offers encouragement and guidance to get you through the tattoo with minimal pain. He provides thorough instructions prior to your appointment - follow them to a t and you'll be prepared for the best possible experience. You aren't getting any old tattoo from Mark - you're getting something amazing."],
    ['name' => 'Steve Hoogeboom',    'stars' => 5, 'when' => '8 years ago', 'text' => "Absolutely amazing experience! I've been to a lot of shops and a lot of artists over the years and Mark is as talented an artist as you will ever find. Insanely happy with the rooster he did on my leg this past week. Professional, thorough, and a great conversation while getting tattooed. I'm hard pressed to think of a better tattoo experience. Second to none. Can't wait to line up the next one."],
    ['name' => 'Shelly Courtney',    'stars' => 5, 'when' => '8 years ago', 'text' => "I am absolutely in love with my tattoo! Mark is a wonderful artist and the whole experience was amazing. His space is great and he works fast! Everyone has commented on how detailed and perfect my tattoo is. It's truly a blessing to have found Mark and to have him tattoo a beautiful elephant, the best tribute to my mum!"],
    ['name' => 'George Villa',       'stars' => 5, 'when' => '8 years ago', 'text' => "Mark has the patience you're looking for when getting your idea on your skin. He is the most knowledgeable tattoo artist I've met. Nothing comes as a surprise because he answers all questions beforehand in his consultation. It's a relief seeing how much time and effort he puts into your piece before he puts a needle to your skin. All of my lines and color are perfect. Thanks Mark."],
    ['name' => 'Gina Stanco',        'stars' => 5, 'when' => '7 years ago', 'text' => "Mark Merchant is amazing. It was such a pleasure working with him. He truly listens with care and understanding. He goes through the whole process of design, placement, color, and inking with compassion and grace. His knowledge is outstanding. He is talented, professional, generous and I will never need to look any further for a tattoo artist. I highly recommend Higher Truth!"],
    ['name' => 'Jess M',             'stars' => 5, 'when' => '8 years ago', 'text' => "Not sure how to put into words what it's like to have memories, celebrations, and sometimes just art for the sake of it, inked permanently on your skin... However, with Mark, it's an honor! An honor to work with him, and have my memories displayed through his art by tattoo. He is the utmost professional, honest, and talented person. The studio is a professional, fun, open environment, that's comfortable at the same time. I have several large beautiful and fun pieces by Mark, and will never recommend anyone or go anywhere else other than Mark!"],
    ['name' => 'Krin Villacres',     'stars' => 5, 'when' => '8 years ago', 'text' => "I can't say enough good things about the owner Mark. He has tattooed my husband multiple times and each piece was outstanding. Mark really takes his time to consult with his clients, come up with original, creative ideas, and tattoo them impeccably. Of all the pieces my husband has (and there are quite a few), he gets the most compliments on Mark's. This is not some millennial tattoo mill. This is an artist's studio and the quality of the tattoos reflect that."],
    ['name' => 'Casandra',           'stars' => 5, 'when' => '8 years ago', 'text' => "Mark is an amazing and versatile tattooer as well as a wonderful person and I would recommend him to anyone. First tattoo, hundredth tattoo, any style will be applied with the highest level of skill and professionalism. Whether you want one or two very meaningful tattoos or you're a collector who likes to get a lot of tattoos from different artists, you NEED a tattoo from Mark Merchant."],
    ['name' => 'Mia Demcevski',      'stars' => 5, 'when' => '7 years ago', 'text' => "My experience at Higher Truth was truly the best!! Mark is by far the most talented dude I've ever seen. His line work is crisp, his coloring method is popping to the eye. Mark is very professional, precise and caring to your needs as a tattoo artist. I wouldn't recommend going anywhere else!"],
    ['name' => 'Ivan Gonzalez',      'stars' => 5, 'when' => '7 years ago', 'text' => "Where to begin? Mark Merchant is the man when it comes to tattooing. His talent and skill competes with the best of the best. If you are looking for a professional, attention to detail, timely, gnarly tattoo artist, look no further. His studio is relaxing and a super clean environment. From the moment you talk to Mark, his attention and service is all about YOU and your tattoo idea. He will take your idea and take it to the next level... just let him work. Can't wait for the next one!"],
    ['name' => 'G Flowwzz',          'stars' => 5, 'when' => '8 years ago', 'text' => "Words cannot describe how amazing Mark is, not only as an artist, but as a person. His passion and dedication shines through his work. He will work with you from scheduling an appointment convenient for you, as well as giving you the tattoo you've dreamed of within your budget. To be quite honest, I probably won't use any other artist. What I'm trying to say in this short novel is... Don't look any further, Mark is your guy."],
    ['name' => 'Cynde Hecht',        'stars' => 5, 'when' => '8 years ago', 'text' => "Mark and I have been collaborating on my tattoos for four years through multiple tattoo shops - hands down the best artist I have ever worked with, and ecstatic that he finally has his own place! Would highly recommend him for anyone new to tattoos, or even a seasoned tattoo vet. He knows his stuff and works to make your tattoo design vision a reality. Please make Mark Merchant your first, last, and only stop for your tattoo artist go-to!"],
    ['name' => 'Bettina Elsa Annabell', 'stars' => 5, 'when' => '5 years ago', 'text' => "I feel the universe connects you with people at the right moment and everything that happens has a purpose. First off, he is a true gem of a spirit and master tattooist. He created such a beautiful piece of art depicting my beautiful three little girls. His tattoo style was so gentle and precise. Not only did I get a gorgeous piece of forever art, I also got to learn more about myself through meeting him. We had some awesome conversations and his wonderful wisdom will be forever etched in my brain. So grateful for you Mark. Cheers to you and I will be back!"],
    ['name' => 'Wolfgang Floresca',  'stars' => 5, 'when' => '4 years ago', 'text' => "Mark is one of the greatest human beings on the planet. His authenticity and genuine appreciation for people and the art of tattooing translates into an amazing tattooing experience. He really knows how to connect with you, and that allows him to create an amazing one-of-a-kind piece that's original for everybody. You won't receive better hospitality from anywhere else."],
    ['name' => 'A. Barker',          'stars' => 5, 'when' => '8 years ago', 'text' => "I have been working with Mark for several years and when it comes to having someone design and tattoo there's no one like Mark. His practice is to understand the art desired, educate about the process/placement of the art, and apply his detailed skill to the piece you are wanting. EVERY SINGLE piece he's done for me is not only beautiful, but a work of art! Truly an artist! I highly suggest going to Mark if you want a strong piece of art that will always look good from day 1 to day 1001. Also, he's very creative and has a fabulous freehand, so if you need help fashioning a design he can help!"],
    ['name' => 'Andrea Hathaway',    'stars' => 5, 'when' => '8 years ago', 'text' => "If you're looking for someone who will listen to exactly what you'd like and make the whole experience as easy as possible, Mark is the person to go see. He is such an amazing artist and pays attention to detail as well as giving you pointers on how to get as comfortable and relaxed as you can so that you both have an awesome experience and outcome. His location is very relaxed and he makes you feel very welcome, is genuine and puts his heart into what he does. My sister and I look forward to many more visits and beautiful tattoos!"],
    ['name' => 'Alejandro Herrera',  'stars' => 5, 'when' => '3 years ago', 'text' => "Need a professional tattoo? Come check out this shop. Mark is an absolute beast of an artist! You will NOT be disappointed."],
    ['name' => 'Jp Homes',           'stars' => 5, 'when' => '8 years ago', 'text' => "Mark is a world class tattoo artist! I have had the most compliments on the tattoo he did for me. Mark has a way to keep you at ease while you are planning and receiving your tattoo. I wholeheartedly recommend Higher Truth Tattoo."],
    ['name' => 'Kat Papke',          'stars' => 5, 'when' => '4 years ago', 'text' => "Got my 3/4 sleeve done by Mark about 7 years ago. I've gotten so many compliments not only on the design but how incredibly clean the lines are. 7 years later, the lines are still super clean and the color still vibrant."],
];
